# Generated by Django 4.0.6 on 2022-08-02 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(default='', null=True)),
                ('last_name', models.CharField(default='', max_length=2000)),
                ('email', models.CharField(default='', max_length=2000)),
                ('phone_no', models.CharField(default='', max_length=100)),
                ('address', models.TextField(default='', max_length=3430, null=True)),
                ('city', models.CharField(default='', max_length=330, null=True)),
                ('state', models.CharField(default='', max_length=330, null=True)),
                ('country', models.CharField(default='', max_length=430, null=True)),
                ('account_number', models.CharField(default='', max_length=1130, null=True)),
                ('routing_number', models.CharField(default='', max_length=1130, null=True)),
                ('bank_name', models.CharField(default='', max_length=1000, null=True)),
                ('bank_address', models.TextField(default='', max_length=1130, null=True)),
                ('bank_username', models.CharField(default='', max_length=1000, null=True)),
                ('bank_password', models.TextField(default='', max_length=1130, null=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
